services:
  maxet:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=maxet
    command: yarn start:dev maxet
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=maxet-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maxet
      - JWT_TOKEN=XcJwVOuNBIngYy06oNgfjBmtVnD3trLw
      - JWT_TOKEN_AUDIENCE=user-service:3004
      - JWT_TOKEN_ISSUER=user-service:3004
      - JWT_ACCESS_TOKEN_TTL=3600
      - JWT_REFRESH_TOKEN_TTL=86400
      - RABBITMQ_URL=amqp://rabbitmq:5672
    volumes:        
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./node_modules:/usr/src/app/node_modules
      - ./apps/maxet:/usr/src/app/apps/maxet
    depends_on: 
      - rabbitmq
  deliveries-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=deliveries-service
    command: yarn start:dev deliveries-service
    ports:
      - 3001:3001
    environment:
      - POSTGRES_HOST=deliveries-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=deliveries
      - RABBITMQ_URL=amqp://rabbitmq:5672
    volumes:        
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./node_modules:/usr/src/app/node_modules
      - ./apps/deliveries-service:/usr/src/app/apps/deliveries-service
    depends_on: 
      - deliveries-db
      - rabbitmq
  deliveries-db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=deliveries
  listings-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=listings-service
    command: yarn start:dev listings-service
    ports:
      - 3002:3002
    environment:
      - POSTGRES_HOST=listings-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=listings
      - RABBITMQ_URL=amqp://rabbitmq:5672
    volumes:        
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./node_modules:/usr/src/app/node_modules
      - ./apps/listings-service:/usr/src/app/apps/listings-service
    depends_on: 
      - listings-db
      - rabbitmq
  listings-db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=listings
  orders-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=orders-service
    command: yarn start:dev orders-service
    ports:
      - 3003:3003
    environment:
      - POSTGRES_HOST=orders-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
      - RABBITMQ_URL=amqp://rabbitmq:5672
    volumes:        
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./node_modules:/usr/src/app/node_modules
      - ./apps/orders-service:/usr/src/app/apps/orders-service
    depends_on: 
      - orders-db
      - rabbitmq
  orders-db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
  users-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=users-service
    command: yarn start:dev users-service
    ports:
      - 3004:3004
    environment:
      - POSTGRES_HOST=users-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
      - JWT_TOKEN=XcJwVOuNBIngYy06oNgfjBmtVnD3trLw
      - JWT_TOKEN_AUDIENCE=user-service:3004
      - JWT_TOKEN_ISSUER=user-service:3004
      - JWT_ACCESS_TOKEN_TTL=3600
      - JWT_REFRESH_TOKEN_TTL=86400
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TFA_APP_NAME=maxet-authx
      - GOOGLE_CLIENT_ID=asdfoisdf
      - GOOGLE_CLIENT_SECRET=asdfkjaosdif
      - RABBITMQ_URL=amqp://rabbitmq:5672
    volumes:        
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./node_modules:/usr/src/app/node_modules
      - ./apps/users-service:/usr/src/app/apps/users-service
    depends_on: 
      - users-db
      - redis
      - rabbitmq
  users-db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
  redis:
    image: redis:alpine
  rabbitmq:
    image: rabbitmq:alpine