services:
  maxet:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=maxet
    command: yarn start:dev maxet
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=maxet-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maxet
    volumes:        
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./node_modules:/usr/src/app/node_modules
      - ./apps/maxet:/usr/src/app/apps/maxet
    depends_on: 
      - maxet-db
  maxet-db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maxet
  deliveries-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=deliveries-service
    command: yarn start:dev deliveries-service
    ports:
      - 3001:3001
    environment:
      - POSTGRES_HOST=deliveries-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=deliveries
    volumes:        
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./node_modules:/usr/src/app/node_modules
      - ./apps/deliveries-service:/usr/src/app/apps/deliveries-service
    depends_on: 
      - deliveries-db
  deliveries-db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=deliveries
  listings-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=listings-service
    command: yarn start:dev listings-service
    ports:
      - 3002:3002
    environment:
      - POSTGRES_HOST=listings-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=listings
    volumes:        
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./node_modules:/usr/src/app/node_modules
      - ./apps/listings-service:/usr/src/app/apps/listings-service
    depends_on: 
      - listings-db
  listings-db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=listings
  orders-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=orders-service
    command: yarn start:dev orders-service
    ports:
      - 3003:3003
    environment:
      - POSTGRES_HOST=orders-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
    volumes:        
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./node_modules:/usr/src/app/node_modules
      - ./apps/orders-service:/usr/src/app/apps/orders-service
    depends_on: 
      - orders-db
  orders-db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
  users-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=users-service
    command: yarn start:dev users-service
    ports:
      - 3004:3004
    environment:
      - POSTGRES_HOST=users-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    volumes:        
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./node_modules:/usr/src/app/node_modules
      - ./apps/users-service:/usr/src/app/apps/users-service
    depends_on: 
      - users-db
  users-db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users